//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4th_point_13_11.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public int id { get; set; }
        public int idProfile { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string patro { get; set; }
        public string mail { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public int series { get; set; }
        public int number { get; set; }
        public System.DateTime birthday { get; set; }
        public string lastEnter { get; set; }
        public Nullable<int> idType { get; set; }
        public int idSex { get; set; }
    
        public virtual profile profile { get; set; }
        public virtual sex sex { get; set; }
        public virtual type type { get; set; }
    }
}
